In [2]:
# arange([ค่าเริ่มต้น],[ค่าสุดท้าย],[ผลต่างระหว่างข้อมูล],[ประเภท])

import numpy as np 

a = np.arange(10)
b = np.arange(3,15)
c = np.arange(2,10,2)
d = np.arange(4,dtype=int)

e = np.arange(1,10,dtype=float)
f = np.arange(1,10,2,dtype=float)

print(a,b,c,d)
print(e,f)

[0 1 2 3 4 5 6 7 8 9] [ 3  4  5  6  7  8  9 10 11 12 13 14] [2 4 6 8] [0 1 2 3]
[1. 2. 3. 4. 5. 6. 7. 8. 9.] [1. 3. 5. 7. 9.]


In [4]:
# what if 

a = np.arange(9,15.5,2)
b = np.arange(-3,2)
c = np.arange(5,2)
d = np.arange(5,2,-2)

print(a,b,c,d)

[ 9. 11. 13. 15.] [-3 -2 -1  0  1] [] [5 3]
