In [1]:
import numpy as np 

a = np.array((1,2,3,4))  # สร้าง ndarray จากข้อมูล Tuple
list_a = [1,2,3,4]    #list
b = np.array(list_a)

print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [2]:
import numpy as np 

a = np.array([[1,2,3],[10,20,30]])  #สร้างอาเรย์ 2 มิติ
b = np.array(('a','b','c'))
c = np.array([[1.5,3.0],[2.5,5.0],[3.5,7.0]])  # list และ tuple


print(a)
print(b)
print(c)

[[ 1  2  3]
 [10 20 30]]
['a' 'b' 'c']
[[1.5 3. ]
 [2.5 5. ]
 [3.5 7. ]]
