In [3]:
import numpy as np 

a = np.arange(12)

print(a)
print('1. a=[2:7]',a[2:7])
print('2. a=[:7]',a[:7])
print('3. a=[2:]',a[2:])
print('4. a=[2:7:3]',a[2:7:3])  #ตั้งแต่ตัวที่2-7 ทีละ3ต่ำแหน่ง
print('5. a=[::4]',a[::4]) # เริ่มที่0 ทีละ4ต่ำแหน่ง
print('5. a=[:-1:2]',a[:-1:2]) 
print('5. a=[2::3]',a[2::3])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1. a=[2:7] [2 3 4 5 6]
2. a=[:7] [0 1 2 3 4 5 6]
3. a=[2:] [ 2  3  4  5  6  7  8  9 10 11]
4. a=[2:7:3] [2 5]
5. a=[::4] [0 4 8]
5. a=[:-1:2] [ 0  2  4  6  8 10]
5. a=[2::3] [ 2  5  8 11]


In [5]:
import numpy as np 

a = np.arange(24).reshape(4,3,2)
print(a)
print('a =')
print('a[1:3:2,::2]')
print(a[1:3:2,::2])

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
a =
a[1:3:2,::2]
[[[ 6  7]
  [10 11]]]
