In [2]:
import numpy as np

a = np.arange(8)

print(a)
print(a[1])
print(a[-2])

[0 1 2 3 4 5 6 7]
1
6


In [3]:
import numpy as np 

a = np.arange(12).reshape(3,4)

print(a)
print(a[2,2])
print(a[-1,-3])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
10
9


In [7]:
import numpy as np 

a = np.arange(12).reshape(3,2,2)

print(a)
print('####')
print(a[2])

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
####
[[ 8  9]
 [10 11]]
