In [16]:
import numpy as np 

a = np.random.randint(100)
print(a)    

78


In [17]:
# anothoer way
from numpy  import random as rd 

a  = rd.randint(100)
print(a)

45


In [20]:
from numpy import random as rd 
# ทำไม่ไดั
#a = rd.randint()
#b = rd.randint(10,5,3)

#print(a)
#print(b)

In [1]:
#randint([ค่าสูงที่สุด])
#randint([ค่าสูงสุด],size = [จำนวนของมิติ ndarray ที่ต้องการ])

from numpy  import random as rd

a = rd.randint(100,size=(10,5,3))
print(a)

[[[54 40 25]
  [81 97 14]
  [48 33 23]
  [32 15  1]
  [ 9 35  1]]

 [[47 70 48]
  [64  3 75]
  [76 15 89]
  [30 68 17]
  [63 30 73]]

 [[50 80 44]
  [88 62 36]
  [94 29 34]
  [97  8 35]
  [55 30 45]]

 [[94 80 51]
  [71 50 26]
  [ 0 76 59]
  [25 60 50]
  [63 60 42]]

 [[95 22 60]
  [35 74 96]
  [32 66 97]
  [24 69 51]
  [86 99 44]]

 [[19  6 53]
  [95 48 48]
  [ 3 32 23]
  [29 92 32]
  [ 5 94 28]]

 [[21 13 21]
  [33 79 89]
  [36  6 82]
  [47 43 86]
  [59 89 44]]

 [[91 87  5]
  [33 67 44]
  [35 58 32]
  [33 75 80]
  [34 71 23]]

 [[19 33 26]
  [92 88 75]
  [34 78 66]
  [80 82 13]
  [93 58 51]]

 [[83 18 42]
  [47 18 36]
  [43  1 30]
  [62 34 31]
  [39 17 94]]]


In [3]:
# shuffle random ต่ำแหน่งเขที่สุ่มอีกที


from numpy  import random as rd 
import numpy  as np

a = np.arange(10)
rd.shuffle(a)

print(a)

[0 5 8 2 1 6 3 7 4 9]
