In [2]:
import numpy as np 
# reshape สร้างมิติ 5x10
a = np.arange(50).reshape(5,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [4]:
import numpy as np 
# reshape สร้างมิติ 5x1
a = np.arange(5).reshape(5,1)
print(a)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [6]:
import numpy as np 
a = np.arange(100).reshape(5,10,2)
b = np.arange(5).reshape(5,1,1)

c = a*b

print(c)

[[[  0   0]
  [  0   0]
  [  0   0]
  [  0   0]
  [  0   0]
  [  0   0]
  [  0   0]
  [  0   0]
  [  0   0]
  [  0   0]]

 [[ 20  21]
  [ 22  23]
  [ 24  25]
  [ 26  27]
  [ 28  29]
  [ 30  31]
  [ 32  33]
  [ 34  35]
  [ 36  37]
  [ 38  39]]

 [[ 80  82]
  [ 84  86]
  [ 88  90]
  [ 92  94]
  [ 96  98]
  [100 102]
  [104 106]
  [108 110]
  [112 114]
  [116 118]]

 [[180 183]
  [186 189]
  [192 195]
  [198 201]
  [204 207]
  [210 213]
  [216 219]
  [222 225]
  [228 231]
  [234 237]]

 [[320 324]
  [328 332]
  [336 340]
  [344 348]
  [352 356]
  [360 364]
  [368 372]
  [376 380]
  [384 388]
  [392 396]]]


In [7]:
import numpy as np 

a = np.arange(50).reshape(5,5,2)
b = np.arange(10).reshape(5,2)

c =a*b
print(c)

[[[  0   1]
  [  4   9]
  [ 16  25]
  [ 36  49]
  [ 64  81]]

 [[  0  11]
  [ 24  39]
  [ 56  75]
  [ 96 119]
  [144 171]]

 [[  0  21]
  [ 44  69]
  [ 96 125]
  [156 189]
  [224 261]]

 [[  0  31]
  [ 64  99]
  [136 175]
  [216 259]
  [304 351]]

 [[  0  41]
  [ 84 129]
  [176 225]
  [276 329]
  [384 441]]]
