In [1]:
import numpy as np 

a = np.arange(50).reshape(5,5,2)
b = np.arange(5).reshape(5,1)

c =a *b 
print(c)                                                                                                                                                           

[[[  0   0]
  [  2   3]
  [  8  10]
  [ 18  21]
  [ 32  36]]

 [[  0   0]
  [ 12  13]
  [ 28  30]
  [ 48  51]
  [ 72  76]]

 [[  0   0]
  [ 22  23]
  [ 48  50]
  [ 78  81]
  [112 116]]

 [[  0   0]
  [ 32  33]
  [ 68  70]
  [108 111]
  [152 156]]

 [[  0   0]
  [ 42  43]
  [ 88  90]
  [138 141]
  [192 196]]]


In [2]:
#ถ้า ndarray 2 ตัวมีมิติที่ท่ากัน และจำนวนสมาชิกที่ต่างกัน 

import numpy as np 
a = np.arange(25).reshape(1,5,5)
b = np.arange(5).reshape(5,1,1)

c = a*b
print(c)

[[[ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]]

 [[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]
  [30 32 34 36 38]
  [40 42 44 46 48]]

 [[ 0  3  6  9 12]
  [15 18 21 24 27]
  [30 33 36 39 42]
  [45 48 51 54 57]
  [60 63 66 69 72]]

 [[ 0  4  8 12 16]
  [20 24 28 32 36]
  [40 44 48 52 56]
  [60 64 68 72 76]
  [80 84 88 92 96]]]


In [5]:
#ถ้า ndarray 2 ตัวมีตัวใดตัวหนึ่งมีจำนวนสมาชิกเป็น1  
import numpy as np 

a = np.arange(12).reshape(4,3)
b= np.array([10])

c = a*b
print(c)

[[  0  10  20]
 [ 30  40  50]
 [ 60  70  80]
 [ 90 100 110]]


In [7]:
# ndarray 2 ตัวไม่สามารถ operation กันได้
import numpy as np 

a = np.arange(20).reshape(4,5)
b = np.arange(20).reshape(10,2)

c = a*b
print(c)

ValueError: operands could not be broadcast together with shapes (4,5) (10,2) 